# Generated by Django 3.2.9 on 2021-11-12 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviephApi', '0002_auto_20211109_1958'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=400)),
            ],
        ),
    ]
