# Generated by Django 3.2.9 on 2021-12-01 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviephApi', '0003_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='star',
            field=models.CharField(default=8, max_length=10),
            preserve_default=False,
        ),
    ]
