# Generated by Django 3.2.9 on 2022-02-08 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviephApi', '0004_movie_star'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='duration',
            field=models.CharField(default='tes', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='genre',
            field=models.CharField(default='test', max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='imdb',
            field=models.CharField(default='test', max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='video_url',
            field=models.CharField(default='test', max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='year',
            field=models.CharField(default='test', max_length=5),
            preserve_default=False,
        ),
    ]
