# Generated by Django 3.2.9 on 2022-02-08 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviephApi', '0005_auto_20220208_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='duration',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='image',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='imdb',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='star',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='video_url',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
