# Generated by Django 3.2.9 on 2022-02-08 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviephApi', '0006_auto_20220208_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='year',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
